app:
  title: Okikiola's IDP
  baseUrl: http://localhost:3000

organization:
  name: Ashiru DevOps

backend:
  baseUrl: http://localhost:7007
  listen:
    port: 7007
  csp:
    connect-src: ["'self'", 'http:', 'https:']
  cors:
    origin: http://localhost:3000
    methods: [GET, HEAD, PATCH, POST, PUT, DELETE]
    credentials: true

  database:
    client: pg
    connection:
      host: 127.0.0.1
      port: 5432
      user: postgres
      password: backstage

    knexConfig:
      acquireConnectionTimeout: 60000
      pool:
        min: 2
        max: 10

integrations:
  github:
    - host: github.com
      token: ${GITHUB_TOKEN}

techdocs:
  builder: 'local'
  generator:
    runIn: 'local'
  publisher:
    type: 'local'

auth:
  environment: development
  providers:
    guest:
      dangerouslyAllowAllRequests: true
    github:
      development:
        clientId: ${AUTH_GITHUB_CLIENT_ID}
        clientSecret: ${AUTH_GITHUB_CLIENT_SECRET}

catalog:
  import:
    entityFilename: catalog-info.yaml
    pullRequestBranchName: backstage-integration
  rules:
    - allow: [Component, System, API, Resource, Location, Template, User, Group]
  locations:
    - type: url
      target: https://github.com/aashiruu/*/blob/main/catalog-info.yaml
      rules:
        - allow: [Component, System, API, Resource, Location]

    - type: file
      target: /home/famous/my-portal/templates/go-service/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: /home/famous/my-portal/examples/guest-user.yaml

    - type: file
      target: /home/famous/my-portal/examples/entities.yaml

permission:
  enabled: false
